# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mech_torso.root] run return 0
execute on passengers if entity @s[tag=aj.mech_torso.data] unless data entity @s {data:{rigHash: '18d4be42d2e70e94f87872f23acb3191e02ca49fb75f6484e116a8f092530168'}} on vehicle run function animated_java:mech_torso/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1