# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mech_torso.root] run return 0
execute on passengers if entity @s[tag=aj.mech_torso.data] unless data entity @s {data:{rigHash: '7cd1e6f81c1a25b3b0c020564725bc60cb04b8f2ed281ad3f1ddc6c418bd7f58'}} on vehicle run function animated_java:mech_torso/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1