# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mech_legs.root] run return 0
execute on passengers if entity @s[tag=aj.mech_legs.data] unless data entity @s {data:{rigHash: '7417a84d40fddecd5b19b5a68488976e9e77d9f44df5b24f799f52bde5549e41'}} on vehicle run function animated_java:mech_legs/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1