# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mech_legs.root] run return 0
execute on passengers if entity @s[tag=aj.mech_legs.data] unless data entity @s {data:{rigHash: '228a0501c36ba6b25e4d74f2b35a1a2f8f589bc97a687034f0d471b46e26c1d3'}} on vehicle run function animated_java:mech_legs/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1