# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.enhancer.root] run return 0
execute on passengers if entity @s[tag=aj.enhancer.data] unless data entity @s {data:{rigHash: '0114a6546cfd00fa7255b5e5243de870a647782928add4dc9f2ca453cc03927c'}} on vehicle run function animated_java:enhancer/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1