# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mech_legs.root] run return 0
execute on passengers if entity @s[tag=aj.mech_legs.data] unless data entity @s {data:{rigHash: '8fbb2a346e00eff7575c9db73c7cd07ff3f80e8de49970bd6f2aa13239ac867d'}} on vehicle run function animated_java:mech_legs/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1