# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fabricator.node.arm_z] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_z set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fabricator.node.nozzle] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_nozzle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fabricator.node.arm_x] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_x set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fabricator.node.frame] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_frame set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fabricator.node.product] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_product set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fabricator.node.bone2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone2 set from storage aj:uuid main.out