# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.assembler.root] run return 0
execute on passengers if entity @s[tag=aj.assembler.data] unless data entity @s {data:{rigHash: '18ae73083e7f2d487b52cee310297db1906b3060deac6e1db2c811c03968f920'}} on vehicle run function animated_java:assembler/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1