# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.fabricator.root] run return 0
execute on passengers if entity @s[tag=aj.fabricator.data] unless data entity @s {data:{rigHash: '96a3c8808220c68d70cba5b8307e8daa438bd52290fc9dea9635c86caf84c428'}} on vehicle run function animated_java:fabricator/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1