# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.fabricator.root] run return 0
execute on passengers if entity @s[tag=aj.fabricator.data] unless data entity @s {data:{rigHash: '8728d0576695c0c785e393901386001f35b97fb56adda8d5f6769410f86dfd4a'}} on vehicle run function animated_java:fabricator/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1