# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mech_torso.root] run return 0
execute on passengers if entity @s[tag=aj.mech_torso.data] unless data entity @s {data:{rigHash: 'd8d3488fb5a41f8ed8c3aa43832fa12f41ef8a85b537a619a1aa5da4665b1ff3'}} on vehicle run function animated_java:mech_torso/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1