# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mech_torso.root] run return 0
execute on passengers if entity @s[tag=aj.mech_torso.data] unless data entity @s {data:{rigHash: '0e3a2107f94fe8548cc0073508c16d847f019a51ff01f33be7cf8ec503327f88'}} on vehicle run function animated_java:mech_torso/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1